### ISSUE TITLE
[UI improvement suggestion]Add some prompts and link to the explorer for swap tx 

### ISSUE THREAD

**Issue by Rbchi** [nervosnetwork/force-bridge#168]
https://force-bridge-dev.ckbapp.dev/bridge/Nervos/Ethereum
Could we lead ppl to the ckb explorer to check their own tx on-chain or not when they completed the swap action(CKB -- > ETH)?

**Comment by homura** [comment]
The UI has a History module that allows ppl to check completed swap actions on the explorer

![image](https://user-images.githubusercontent.com/7511174/126022737-608f7eab-b578-4ab9-b9d9-1a3ba5e95bae.png)

**Comment by Rbchi** [comment]
Have found it.Thanks for your replying. I am just new for FB's UI

**Comment by homura** [comment]
This issue have been resolved and I will be closing it. Feel free to new an issue when you getting stuck and we'll comment as soon
