### ISSUE TITLE
Bridge BSC, info says 'lock asset on Ethereum'

### ISSUE THREAD

**Issue by yixyxiu** [nervosnetwork/force-bridge#276]
The testnet, as shown, bridges BNB, an asset of BSC, but says 'lock asset on Ethereum', which can be confusing to users. Both pending and succeed forms have the same issue.

![image](https://user-images.githubusercontent.com/87553548/147574533-f4cca609-fcbc-46e5-935a-c35bd1604955.png)

**Comment by huwenchao** [comment]
Thanks for reporting. We are on fixing that.

**Comment by mkxbl** [comment]
Fixed:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/33241113/149279879-3e77b299-5c80-4c3c-a8a5-bc0ad0e281a7.png">
