### ISSUE TITLE
Force Bridge Screen Blank

### ISSUE THREAD

**Issue by hemanthbseo** [nervosnetwork/force-bridge#291]
I’m still new to new to Nervos Force Bridge. I visited the https://forcebridge.com/bridge/ link to participate in BNB ILO. As per the instructions on the medium article, I selected BSC-> Nervos at the top of the page. But the screen is blank. Nothing shows up below.

I have my BNB on  Binance.

![image](https://user-images.githubusercontent.com/62465493/149273537-d49f34c1-a8d9-43fb-b9bd-d49526603fbc.png)

What am I doing wrong? Please help.

**Comment by mkxbl** [comment]
Please visit https://forcebridge.com , rather than https://forcebridge.com/bridge/

**Comment by hemanthbseo** [comment]
Thank you! You are a star!
