### ISSUE TITLE
Bridge don't work

### ISSUE THREAD

**Issue by Gondagar** [nervosnetwork/force-bridge#318]
Bridge don't work via safepal app. Can't connect to metamask

**Comment by huwenchao** [comment]
Safepal does not support switch network api, you have to switch the network manually.

![telegram-cloud-photo-size-5-6095916043663945467-y](https://user-images.githubusercontent.com/1630721/154881046-e85857c7-ba01-4ad6-8a6c-317d797de92e.jpg)

Try following the instructions below.

Select the network as below.

![2022-02-21 10 50 19](https://user-images.githubusercontent.com/1630721/154881217-3ac6b8f9-667f-4ef8-b8cd-6228bfb19107.jpg)

![telegram-cloud-photo-size-5-6095916043663945469-y](https://user-images.githubusercontent.com/1630721/154881282-03b93fda-3c3f-4632-87c7-d2c0c8216d5e.jpg)

Select the bridge direction and click `connect a wallet to start`.

![2022-02-21 10 52 41](https://user-images.githubusercontent.com/1630721/154881372-8d3aae3d-e6b0-4814-a51a-5d2ba680eb6b.jpg)
