### ISSUE TITLE
short address ckb (nervos)

### ISSUE THREAD

**Issue by merakmember** [nervosnetwork/force-bridge#319]
when is the short address feature of ckb (nervos) in publication ? 
I have a BNB|bsc balance stuck at the short address ckb (nervos).

Because i entered short address when using force-bridge

https://bscscan.com/tx/0x0c2501f62c3b2c4600f0ee8bac5ef77ae5b10ba628e849cb036842b78b5581c6

https://explorer.nervos.org/address/ckb1qyqw5az0fv2dwf9q7a080d5qgp4mrqwctzxs7gtxvf

**Comment by huwenchao** [comment]
The bnb asset is safe in the short address. But there is no wallets for short address support transfer sudt right now. I believe Neuron is working on this. Not sure about the timeline. Open an issue in their repo to ask if you are interested.
https://github.com/nervosnetwork/neuron

**Comment by merakmember** [comment]
> The bnb asset is safe in the short address. But there is no wallets for short address support transfer sudt right now. I believe Neuron is working on this. Not sure about the timeline. Open an issue in their repo to ask if you are interested. https://github.com/nervosnetwork/neuron

thanks for information
