### ISSUE TITLE
how to connect safepal wallet

### ISSUE THREAD

**Issue by fouzanmohd** [nervosnetwork/force-bridge#320]
Safepal wallet does not support metamask, so if we want to migrate the coins in safepal wallet address there is no way to connect to the DAPP, 
how to connect safepal wallet to this dapp and migrate the tokens?

**Comment by huwenchao** [comment]
The pw-up tool already supported safepal: https://github.com/homura/pw-up/pull/19

Please try again.

https://pw-up.vercel.app/
