### ISSUE TITLE
Script Server Error

### ISSUE THREAD

**Issue by Hb0713** [nervosnetwork/force-bridge#321]
While trying to use force bridge with Safepal, I receive a script error. I am trying to send Usdc(Nervos L1) to Usdc (erc20) using Nervos --> Eth in the force bridge. I am able to see my usdc/eth. I enter my eth address, click "Bridge" and receive the attached error. I am using eth mainnet
![SmartSelect_20220220-170113](https://user-images.githubusercontent.com/100173829/155044482-08ddd38b-893f-4aff-9140-c36af682c638.jpg)
![SmartSelect_20220220-170151](https://user-images.githubusercontent.com/100173829/155044483-6ca5c0a1-5a18-4c2b-800a-b24add71c65a.jpg)

**Comment by herculesbeetle** [comment]
I have the same problem, try to bridge bnb|bsc[nervos] to safepal wallet. Can anyone help me please?
![28381](https://user-images.githubusercontent.com/92709058/155580185-5e68cab0-492d-40a7-87b6-385e09068d50.jpg)

**Comment by huwenchao** [comment]
https://github.com/nervosnetwork/force-bridge-ui/issues/103

It's the ethereum provider compatibility issue.

Already fixed.
